# Generated by Django 3.1.7 on 2021-07-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
