# Generated by Django 3.1.7 on 2021-07-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
